project '/Volumes/MacSSD/Projects/iOS Development/LogInUI/LogInUI.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LogInUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'IQKeyboardManagerSwift'
  # Pods for LogInUI

end
